---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
  - tests/
  - "src/NorthEastEvents/Models/Base/"
  - "src/NorthEastEvents/Models/Map/"
