version: '2'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./conf/nginx/nginx.docker.conf:/etc/nginx/conf.d/default.conf
  php:
    image: bitnami/php-fpm
    volumes:
      - .:/var/www
      - ./src:/app
      - ./logs/php:/bitnami/php-fpm/logs/
      - ./conf/php:/bitnami/php-fpm/conf/
    ports:
      - "9001:9000"
    environment:
      - PATH=/opt/bitnami/php/sbin:/opt/bitnami/php/bin:/opt/bitnami/common/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/src/vendor/bin:/var/www/src/vendor/propel/propel/bin
  db:
    image: mariadb
    ports:
      - "3307:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=vagrant
     - MYSQL_DATABASE=north_east_charity
     - MYSQL_USER=northeast
     - MYSQL_PASSWORD=charity
